# Tensor

`Ascend` `GPU` `CPU` `Beginner`

[Tensor](https://www.mindspore.cn/docs/api/en/master/api_python/mindspore/mindspore.Tensor.html) is a basic data structure in the MindSpore network computing. This chapter mainly introduces the properties and usage of tensors and sparse tensors.

First, prepare the environment required to run this document. In this document, the mode is set to Graph mode, and the hardware is set to CPU. Users can configure it according to the actual environment.

In [1]:
from mindspore import context

context.set_context(mode=context.GRAPH_MODE, device_target="CPU")

## Initializing a Tensor

There are multiple methods for initializing tensors. When building a tensor, you can pass the Tensor with `float`, `int`, `bool`, `tuple`, `list`, and `NumPy.array` types.

- **Generate a tensor based on data.**

You can create a tensor based on data. The data type can be set or automatically inferred.

In [2]:
from mindspore import Tensor

x = Tensor(0.1)

- **Generate a tensor from the NumPy array.**

You can create a tensor from the NumPy array.

In [3]:
import numpy as np

arr = np.array([1, 0, 1, 0])
x_np = Tensor(arr)

If the initial value is `NumPy.array`, the generated `Tensor` data type corresponds to `NumPy.array`.

- **Generate a tensor from the init**

You can create a tensor with the `init`, `shape` and `dtype`.

- `init`: Supported subclasses of incoming Subclass of [initializer](https://www.mindspore.cn/docs/api/en/master/api_python/mindspore.common.initializer.html).
- `shape`: Supported subclasses of incoming `list`, `tuple`, `int`.
- `dtype`: Supported subclasses of incoming [mindspore.dtype](https://www.mindspore.cn/docs/api/en/master/api_python/mindspore.html#mindspore.dtype).

In [4]:
from mindspore import Tensor
from mindspore import set_seed
from mindspore import dtype as mstype
from mindspore.common.initializer import One, Normal

set_seed(1)

tensor1 = Tensor(shape=(2, 2), dtype=mstype.float32, init=One())
tensor2 = Tensor(shape=(2, 2), dtype=mstype.float32, init=Normal())
print(tensor1)
print(tensor2)

[[1. 1.]
 [1. 1.]]
[[-0.00128023 -0.01392901]
 [ 0.0130886  -0.00107818]]


The `init` is used for delayed initialization in parallel mode. Usually, it is not recommended to use `init` interface to initialize parameters in other conditions.

- **Inherit attributes of another tensor to form a new tensor.**

In [5]:
from mindspore import ops

oneslike = ops.OnesLike()
x = Tensor(np.array([[0, 1], [2, 1]]).astype(np.int32))
output = oneslike(x)
print(output)

[[1 1]
 [1 1]]


- **Output a constant tensor of a specified size.**

`shape` is the size tuple of a tensor, which determines the dimension of the output tensor.

In [6]:
shape = (2, 2)
ones = ops.Ones()
output = ones(shape, mstype.float32)
print(output)

zeros = ops.Zeros()
output = zeros(shape, mstype.float32)
print(output)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


During `Tensor` initialization, dtype can be specified to, for example, `mstype.int32`, `mstype.float32` or `mstype.bool_`.

## Tensor Attributes

Tensor attributes include shape, data type, transposed tensor, item size, number of bytes occupied, dimension, size of elements, and stride per dimension.

- shape: the shape of `Tensor`, it is a tuple.

- dtype: the dtype of `Tensor`, it is a data type of MindSpore.

- T: the Transpose of `Tensor`, it is also a `Tensor`.

- itemsize: the number of bytes occupied by each element in `Tensor` is an integer.

- nbytes: the total number of bytes occupied by `Tensor`, as an integer.

- ndim: the rank of a `Tensor`, which is len(tensor.shape), is an integer.

- size: the number of all elements in `Tensor`, it is an integer.

- strides: the number of bytes to traverse in each dimension of `Tensor`.

In [7]:
x = Tensor(np.array([[1, 2], [3, 4]]), mstype.int32)

print("x_shape:", x.shape)
print("x_dtype:", x.dtype)
print("x_transposed:\n", x.T)
print("x_itemsize:", x.itemsize)
print("x_nbytes:", x.nbytes)
print("x_ndim:", x.ndim)
print("x_size:", x.size)
print("x_strides:", x.strides)

x_shape: (2, 2)
x_dtype: Int32
x_transposed:
 [[1 3]
 [2 4]]
x_itemsize: 4
x_nbytes: 16
x_ndim: 2
x_size: 4
x_strides: (8, 4)


## Index

Tensor indexing is similar to Numpy indexing, indexing starts from 0, negative indexing means indexing in reverse order, and colons `:` and `...` are used for slicing.

In [8]:
tensor = Tensor(np.array([[0, 1], [2, 3]]).astype(np.float32))
print("First row: {}".format(tensor[0]))
print("value of top right corner: {}".format(tensor[1, 1]))
print("Last column: {}".format(tensor[:, -1]))
print("First column: {}".format(tensor[..., 0]))

First row: [0. 1.]
value of top right corner: 3.0
Last column: [1. 3.]
First column: [0. 2.]


## Tensor Operation

There are many operations between tensors, including arithmetic, linear algebra, matrix processing (transposing, indexing, and slicing), and sampling. The following describes several operations. The usage of tensor computation is similar to that of NumPy.

Common arithmetic operations include: addition (+), subtraction (-), multiplication (\*), division (/), modulo (%), power (\*\*), and exact division (//).

In [9]:
x = Tensor(np.array([1.0, 2.0, 3.0]), mstype.float32)
y = Tensor(np.array([4.0, 5.0, 6.0]), mstype.float32)

output_add = x + y
output_sub = x - y
output_mul = x * y
output_div = y / x
output_mod = x % y
output_pow = x ** 2
output_floordiv = y // x

print("add:", output_add)
print("sub:", output_sub)
print("mul:", output_mul)
print("div:", output_div)
print("mod:", output_mod)
print("pow:", output_pow)
print("floordiv:", output_floordiv)

add: [5. 7. 9.]
sub: [-3. -3. -3.]
mul: [ 4. 10. 18.]
div: [4.  2.5 2. ]
mod: [1. 2. 3.]
pow: [1. 4. 9.]
floordiv: [4. 2. 2.]


`Concat` connects a series of tensors in a given dimension.

In [10]:
data1 = Tensor(np.array([[0, 1], [2, 3]]).astype(np.float32))
data2 = Tensor(np.array([[4, 5], [6, 7]]).astype(np.float32))
op = ops.Concat()
output = op((data1, data2))
print(output)

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]]


`Stack` combines two tensors from another dimension.

In [11]:
data1 = Tensor(np.array([[0, 1], [2, 3]]).astype(np.float32))
data2 = Tensor(np.array([[4, 5], [6, 7]]).astype(np.float32))
op = ops.Stack()
output = op([data1, data2])
print(output)

[[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]


## Conversion Between Tensor and NumPy

Tensor and NumPy can be converted to each other.

### Tensor to NumPy

Use `asnumpy()` to convert Tensor to NumPy.

In [12]:
zeros = ops.Zeros()
output = zeros((2, 2), mstype.float32)
print("output: {}".format(type(output)))
n_output = output.asnumpy()
print("n_output: {}".format(type(n_output)))

output: <class 'mindspore.common.tensor.Tensor'>
n_output: <class 'numpy.ndarray'>


### NumPy to Tensor

Use `asnumpy()` to convert NumPy to Tensor.

In [13]:
output = np.array([1, 0, 1, 0])
print("output: {}".format(type(output)))
t_output = Tensor(output)
print("t_output: {}".format(type(t_output)))

output: <class 'numpy.ndarray'>
t_output: <class 'mindspore.common.tensor.Tensor'>


## Sparse Tensor

A sparse tensor is a special kind of tensor in which the number of elements with a value of 0 is much greater than the number of non-zero elements. In some application scenarios (such as recommendation systems), the features of the data are sparse, and using ordinary tensors to represent these data will introduce a lot of unnecessary computational, storage, and communication overhead. At such times, sparse tensors can be used to represent the data. MindSpore has two sparse tensor structures, `SparseTensor` and `RowTensor`.

> Currently, sparse tensor is not supported in PyNative mode.

### SparseTensor

`SparseTensor` is used to compress Tensors with irregular distribution of non-zero elements. If the number of non-zero elements is `N` and the dimension of the compressed tensor is `ndims`, there are:

- `indices`: two-dimensional integer tensor, each row represents a non-zero element index, shape: `[N, ndims]`.

- `values`: one-dimensional tensor, representing the value of the corresponding non-zero element, shape: `[N]`.

- `dense_shape`: represents the shape of the compressed sparse tensor.

`SparseTensor` can only be used in the construction method of `Cell`, use `SparseTensor` to create the following sparse tensor, the tensor shape is (3, 4):

![SparseTensor](https://gitee.com/mindspore/docs/raw/tutorials-develop/tutorials/source_en/beginner/images/tensor_1.PNG)


In [14]:
from mindspore import SparseTensor
import mindspore.nn as nn

class Net(nn.Cell):
    def __init__(self, dense_shape):
        super(Net, self).__init__()
        self.dense_shape = dense_shape
    def construct(self, indices, values):
        x = SparseTensor(indices, values, self.dense_shape)
        return x.values, x.indices, x.dense_shape

indices = Tensor([[0, 1], [1, 2]])
values = Tensor([1, 2], dtype=mstype.float32)
out = Net((3, 4))(indices, values)
print("non-zero values:", out[0])
print("non-zero indices:\n", out[1])
print("shape:", out[2])

non-zero values: [1. 2.]
non-zero indices:
 [[0 1]
 [1 2]]
shape: (3, 4)


### RowTensor

`RowTensor` is used to compress tensors that are sparse in the zeroth dimension. If the dimension of `RowTensor` is `[L0, D1, D2, ..., DN ]`. The number of non-zero elements in the zeroth dimension is `D0`, then `L0 >> D0`.

- `indices`: one-dimensional integer tensor representing the position of non-zero elements in the zeroth dimension of the sparse tensor, shape: `[D0]`.

- `values`: represents the value of the corresponding non-zero element, shape: `[D0, D1, D2, ..., DN]`.

- `dense_shape`: represents the shape of the compressed sparse tensor.

> `RowTensor` can only be used in the constructor of `Cell`.

In [15]:
from mindspore import RowTensor
import mindspore.nn as nn

class Net(nn.Cell):
    def __init__(self, dense_shape):
        super(Net, self).__init__()
        self.dense_shape = dense_shape
    def construct(self, indices, values):
        x = RowTensor(indices, values, self.dense_shape)
        return x.values, x.indices, x.dense_shape

indices = Tensor([0])
values = Tensor([[1, 2]], dtype=mstype.float32)
out = Net((3, 2))(indices, values)
print("non-zero values:", out[0])
print("non-zero indices:", out[1])
print("shape:", out[2])

non-zero values: [[1. 2.]]
non-zero indices: [0]
shape: (3, 2)
