# 张量

`Ascend` `GPU` `CPU` `入门`

[![在线运行](https://gitee.com/mindspore/docs/raw/master/resource/_static/logo_modelarts.png)](https://authoring-modelarts-cnnorth4.huaweicloud.com/console/lab?share-url-b64=aHR0cHM6Ly9taW5kc3BvcmUtd2Vic2l0ZS5vYnMuY24tbm9ydGgtNC5teWh1YXdlaWNsb3VkLmNvbS9ub3RlYm9vay9tb2RlbGFydHMvcXVpY2tfc3RhcnQvbWluZHNwb3JlX3RlbnNvci5pcHluYg==&imageid=65f636a0-56cf-49df-b941-7d2a07ba8c8c)&emsp;[![下载Notebook](https://gitee.com/mindspore/docs/raw/master/resource/_static/logo_notebook.png)](https://obs.dualstack.cn-north-4.myhuaweicloud.com/mindspore-website/notebook/master/tutorials/zh_cn/mindspore_tensor.ipynb)&emsp;[![下载样例代码](https://gitee.com/mindspore/docs/raw/master/resource/_static/logo_download_code.png)](https://obs.dualstack.cn-north-4.myhuaweicloud.com/mindspore-website/notebook/master/tutorials/zh_cn/mindspore_tensor.py)
&emsp;[![查看源文件](https://gitee.com/mindspore/docs/raw/master/resource/_static/logo_source.png)](https://gitee.com/mindspore/docs/blob/master/tutorials/source_zh_cn/beginner/tensor.ipynb)

张量（[Tensor](https://www.mindspore.cn/docs/api/zh-CN/master/api_python/mindspore/mindspore.Tensor.html)）是MindSpore网络运算中的基本数据结构，本章主要介绍张量和稀疏张量的属性及用法。

首先准备本文档运行所需的环境，本文档将模式设置为静态图模式，硬件设置为CPU，用户可根据实际环境进行相应的配置。

In [3]:
from mindspore import context

context.set_context(mode=context.GRAPH_MODE, device_target="CPU")

## 初始化张量

张量的初始化方式有多种，构造张量时，支持传入`Tensor`、`float`、`int`、`bool`、`tuple`、`list`和`NumPy.array`类型。

- **根据数据直接生成**

可以根据数据创建张量，数据类型可以设置或者通过框架自动推断。

In [4]:
from mindspore import Tensor

x = Tensor(0.1)

- **从NumPy数组生成**

可以从NumPy数组创建张量。

In [5]:
import numpy as np

arr = np.array([1, 0, 1, 0])
x_np = Tensor(arr)

初始值是`NumPy.array`，则生成的`Tensor`数据类型与之对应。

- **使用init初始化器构造张量**

当使用`init`初始化器对张量进行初始化时，支持传入的参数有`init`、`shape`、`dtype`。

- `init`: 支持传入[initializer](https://www.mindspore.cn/docs/api/zh-CN/master/api_python/mindspore.common.initializer.html)的子类。

- `shape`: 支持传入 `list`、`tuple`、 `int`。

- `dtype`: 支持传入[mindspore.dtype](https://www.mindspore.cn/docs/api/zh-CN/master/api_python/mindspore.html#mindspore.dtype)。

In [6]:
from mindspore import Tensor
from mindspore import set_seed
from mindspore import dtype as mstype
from mindspore.common.initializer import One, Normal

set_seed(1)

tensor1 = Tensor(shape=(2, 2), dtype=mstype.float32, init=One())
tensor2 = Tensor(shape=(2, 2), dtype=mstype.float32, init=Normal())
print(tensor1)
print(tensor2)

[[1. 1.]
 [1. 1.]]
[[-0.00128023 -0.01392901]
 [ 0.0130886  -0.00107818]]


`init`主要用于并行模式下的延后初始化，在正常情况下不建议使用init对参数进行初始化。

- **继承另一个张量的属性，形成新的张量**

In [7]:
from mindspore import ops

oneslike = ops.OnesLike()
x = Tensor(np.array([[0, 1], [2, 1]]).astype(np.int32))
output = oneslike(x)
print(output)

[[1 1]
 [1 1]]


[WARNING] DEBUG(9214,7f617605b740,python):2022-02-11-14:30:06.774.948 [mindspore/ccsrc/debug/debugger/debugger.cc:92] Debugger] Not enabling debugger. Debugger does not support CPU.


- **输出指定大小的恒定值张量**

`shape`是张量的尺寸元组，确定输出的张量的维度。

In [8]:
shape = (2, 2)
ones = ops.Ones()
output = ones(shape, mstype.float32)
print(output)

zeros = ops.Zeros()
output = zeros(shape, mstype.float32)
print(output)

[[1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]]


`Tensor`初始化时，可指定dtype，如`mstype.int32`、`mstype.float32`、`mstype.bool_`等。

## 张量的属性

张量的属性包括形状、数据类型、转置张量、单个元素大小、占用字节数量、维数、元素个数和每一维步长。

- 形状（shape）：`Tensor`的shape，是一个tuple。

- 数据类型（dtype）：`Tensor`的dtype，是MindSpore的一个数据类型。

- 转置张量（T）：`Tensor`的转置，是一个`Tensor`。

- 单个元素大小（itemsize）： `Tensor`中每一个元素占用字节数，是一个整数。

- 占用字节数量（nbytes）： `Tensor`占用的总字节数，是一个整数。

- 维数（ndim）： `Tensor`的秩，也就是len(tensor.shape)，是一个整数。

- 元素个数（size）： `Tensor`中所有元素的个数，是一个整数。

- 每一维步长（strides）： `Tensor`每一维所需要的字节数，是一个tuple。

In [9]:
x = Tensor(np.array([[1, 2], [3, 4]]), mstype.int32)

print("x_shape:", x.shape)
print("x_dtype:", x.dtype)
print("x_transposed:\n", x.T)
print("x_itemsize:", x.itemsize)
print("x_nbytes:", x.nbytes)
print("x_ndim:", x.ndim)
print("x_size:", x.size)
print("x_strides:", x.strides)

x_shape: (2, 2)
x_dtype: Int32
x_transposed:
 [[1 3]
 [2 4]]
x_itemsize: 4
x_nbytes: 16
x_ndim: 2
x_size: 4
x_strides: (8, 4)


## 索引

Tensor索引与Numpy索引类似，索引从0开始编制，负索引表示按倒序编制，冒号`:`和 `...`用于切片。

In [10]:
tensor = Tensor(np.array([[0, 1], [2, 3]]).astype(np.float32))
print("First row: {}".format(tensor[0]))
print("value of top right corner: {}".format(tensor[1, 1]))
print("Last column: {}".format(tensor[:, -1]))
print("First column: {}".format(tensor[..., 0]))

First row: [0. 1.]
value of top right corner: 3.0
Last column: [1. 3.]
First column: [0. 2.]


## 张量运算

张量之间有很多运算，包括算术、线性代数、矩阵处理（转置、标引、切片）、采样等，张量运算和NumPy的使用方式类似，下面介绍其中几种操作。

普通算术运算有：加（+）、减（-）、乘（\*）、除（/）、取模（%）、幂次方（\*\*）、整除（//）。

In [11]:
x = Tensor(np.array([1.0, 2.0, 3.0]), mstype.float32)
y = Tensor(np.array([4.0, 5.0, 6.0]), mstype.float32)

output_add = x + y
output_sub = x - y
output_mul = x * y
output_div = y / x
output_mod = x % y
output_pow = x ** 2
output_floordiv = y // x

print("add:", output_add)
print("sub:", output_sub)
print("mul:", output_mul)
print("div:", output_div)
print("mod:", output_mod)
print("pow:", output_pow)
print("floordiv:", output_floordiv)

add: [5. 7. 9.]
sub: [-3. -3. -3.]
mul: [ 4. 10. 18.]
div: [4.  2.5 2. ]
mod: [1. 2. 3.]
pow: [1. 4. 9.]
floordiv: [4. 2. 2.]


`Concat`将给定维度上的一系列张量连接起来。

In [12]:
data1 = Tensor(np.array([[0, 1], [2, 3]]).astype(np.float32))
data2 = Tensor(np.array([[4, 5], [6, 7]]).astype(np.float32))
op = ops.Concat()
output = op((data1, data2))
print(output)

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]]


`Stack`则是从另一个维度上将两个张量合并起来。

In [13]:
data1 = Tensor(np.array([[0, 1], [2, 3]]).astype(np.float32))
data2 = Tensor(np.array([[4, 5], [6, 7]]).astype(np.float32))
op = ops.Stack()
output = op([data1, data2])
print(output)

[[[0. 1.]
  [2. 3.]]

 [[4. 5.]
  [6. 7.]]]


## 与NumPy转换

张量可以和NumPy进行互相转换。

### 张量转换为NumPy

使用 `asnumpy()` 将Tensor变量转换为NumPy变量。

In [14]:
zeros = ops.Zeros()
output = zeros((2, 2), mstype.float32)
print("output: {}".format(type(output)))
n_output = output.asnumpy()
print("n_output: {}".format(type(n_output)))

output: <class 'mindspore.common.tensor.Tensor'>
n_output: <class 'numpy.ndarray'>


### NumPy转换为张量

使用`Tensor()`将NumPy变量转换为Tensor变量。

In [15]:
output = np.array([1, 0, 1, 0])
print("output: {}".format(type(output)))
t_output = Tensor(output)
print("t_output: {}".format(type(t_output)))

output: <class 'numpy.ndarray'>
t_output: <class 'mindspore.common.tensor.Tensor'>


## 稀疏张量

稀疏张量是一种特殊张量，其中数值为0的元素数目远远大于非0元素的数目。在某些应用场景中（比如推荐系统），数据的特征是稀疏的，若使用普通张量表征这些数据会引入大量不必要的计算、存储和通讯开销，这时就可以使用稀疏张量来表征这些数据。MindSpore有 `SparseTensor` 和 `RowTensor`两种稀疏张量结构。

### SparseTensor

`SparseTensor`用于压缩非零元素位置分布不规则的张量，若非零元素的个数为`N`，被压缩的张量的维数为`ndims`，则有：

- `indices`: 二维整数张量，每行代表非零元素下标，形状为`[N, ndims]`。

- `values`: 一维张量，表示相对应的非零元素的值，形状为`[N]`。

- `dense_shape`: 表示的是被压缩的稀疏张量的形状。

使用`SparseTensor`创建如下稀疏张量，张量shape为（3，4）：
![SparseTensor](https://gitee.com/mindspore/docs/raw/tutorials-develop/tutorials/source_zh_cn/beginner/images/tensor_1.PNG)

In [17]:
from mindspore import Tensor, SparseTensor
import mindspore.nn as nn
import mindspore.context as context

context.set_context(mode=context.PYNATIVE_MODE)
indices = Tensor([[0, 1], [1, 2]])
values = Tensor([1, 2], dtype=mstype.int32)
dense_shape = (3, 4)
sparse_tensor = SparseTensor(indices, values, dense_shape)
sparse_to_dense = nn.SparseToDense()
result = sparse_to_dense(sparse_tensor)
print(result)

[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 0]]


### RowTensor

`RowTensor`用于压缩第零个维度稀疏的张量。若`RowTensor`的维度为`[L0, D1, D2, ..., DN ]`。第零维度的非零元素个数为`D0`, 则有`L0 >> D0`。

- `indices`: 一维整数张量，表示稀疏张量第零维度中非零元素的位置，形状为`[D0]`。

- `values`: 表示相对应的非零元素的值，形状为`[D0, D1, D2, ..., DN]`。

- `dense_shape`: 表示的是被压缩的稀疏张量的形状。

> `RowTensor`只能在`Cell`的构造方法中使用。

In [19]:
from mindspore import RowTensor
import mindspore.nn as nn

class Net(nn.Cell):
    def __init__(self, dense_shape):
        super(Net, self).__init__()
        self.dense_shape = dense_shape
    def construct(self, indices, values):
        x = RowTensor(indices, values, self.dense_shape)
        return x.values, x.indices, x.dense_shape

indices = Tensor([0])
values = Tensor([[1, 2]], dtype=mstype.float32)
out = Net((3, 2))(indices, values)
print("non-zero values:", out[0])
print("non-zero indices:", out[1])
print("shape:", out[2])

non-zero values: [[1. 2.]]
non-zero indices: [0]
shape: (3, 2)
